test_traceroute_aspath.py: Fix ASPATH expectations
It seems real probe generates slightly different ASPATH,
as result tests are failing:
```
============================================================================================= short test summary info =============================================================================================
FAILED tests/renderers/test_traceroute_aspath.py::TestTracerouteASPathRenderer::test_arg_radius - AssertionError: Lists differ: ['Pro[33 chars]4637 AS207021, completed', 'Probe #22880:  AS2[215 chars], ''] != ['Pro[33 chars]4637   AS1921, completed', 'Probe #22880:  AS2[215 chars], '']
FAILED tests/renderers/test_traceroute_aspath.py::TestTracerouteASPathRenderer::test_basic - AssertionError: Lists differ: ['Pro[15 chars]4637 AS207021, completed', 'Probe #22880:   AS[117 chars], ''] != ['Pro[15 chars]4637   AS1921, completed', 'Probe #22880:   AS[117 chars], '']
FAILED tests/test_docs.py::DocTest::test_html_documentation - sphinx.errors.SphinxWarning: Failed to read intersphinx_mapping[http://docs.python.org/], ignored: SphinxWarning('The pre-Sphinx 1.0 \'intersphinx_mapping\' format is deprecated and will be removed in Sphin...
```

This commit updating it to the actual one.

Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>